[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "llm-proxypy"
version = "0.0.6"
authors = [
    {name = "shlll", email = "shlll7347@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.7"
description = "llm proxy server"
dependencies = [
    "pyjwt",
    "pyyaml",
    # "shutilspy @ git+https://github.com/shlllshlll/shutilspy.git@master"
]

[project.optional-dependencies]
requests = ["requests"]
httpx = ["httpx"]
aiohttp = ["aiohttp"]
fastapi = ["fastapi"]
flask = ["flask"]

[tool.setuptools]
packages = ["llm_proxy", "llm_proxy.param", "llm_proxy.provider"]
